from planet import  Planet,Direction
from erkunder import Erkunder
planet = Planet()
erkunder = Erkunder(planet)
erkunder.add_start_scann((0,0),[Direction.EAST,Direction.SOUTH])
print(erkunder.get_new_direction())
erkunder.add_new_scann((1,0),[Direction.WEST,Direction.SOUTH],Direction.WEST)
print(erkunder.get_new_direction())
erkunder.add_new_scann((1,1),[Direction.WEST,Direction.SOUTH,Direction.NORTH],Direction.NORTH)
print(erkunder.get_new_direction())
erkunder.add_new_scann((0,1),[Direction.EAST,Direction.SOUTH,Direction.NORTH],Direction.EAST)
print(erkunder.get_new_direction())
erkunder.add_new_scann((1,2),[Direction.WEST,Direction.NORTH],Direction.WEST)
print(erkunder.get_new_direction())
erkunder.add_new_scann((1,1),[Direction.WEST,Direction.SOUTH,Direction.NORTH],Direction.SOUTH)
print(erkunder.get_new_direction())
erkunder.add_new_scann((1,2),[Direction.WEST,Direction.NORTH],Direction.WEST)
print(erkunder.get_new_direction())
erkunder.add_new_scann((0,1),[Direction.EAST,Direction.SOUTH,Direction.NORTH],Direction.SOUTH)
print(erkunder.get_new_direction())
erkunder.add_new_scann((0,0),[Direction.EAST,Direction.SOUTH],Direction.SOUTH)
print(erkunder.get_new_direction())
erkunder.add_new_scann((0,1),[Direction.EAST,Direction.SOUTH,Direction.NORTH],Direction.NORTH)
print(erkunder.get_new_direction())
