from planet import  Planet,Direction
from explorer import Explorer
planet = Planet()
explorer = Explorer(planet)
explorer.add_start_scann((0, 0), [Direction.WEST, Direction.EAST, Direction.SOUTH])
print(explorer.get_next_direction())
explorer.set_choosed_direction(explorer.get_next_direction())
explorer.add_new_scann((0, 0), [Direction.WEST, Direction.EAST, Direction.SOUTH], Direction.WEST,1)
print(explorer.get_next_direction())
explorer.set_choosed_direction(explorer.get_next_direction())
explorer.add_new_scann((1, 0), [Direction.WEST, Direction.SOUTH], Direction.WEST,1)
print(explorer.get_next_direction())
explorer.set_choosed_direction(explorer.get_next_direction())
explorer.add_new_scann((1, 1), [Direction.WEST, Direction.SOUTH, Direction.NORTH], Direction.NORTH,1)
print(explorer.get_next_direction())
explorer.set_choosed_direction(explorer.get_next_direction())
explorer.add_new_scann((0, 1), [Direction.EAST, Direction.SOUTH, Direction.NORTH], Direction.EAST,1)
print(explorer.get_next_direction())
explorer.set_choosed_direction(explorer.get_next_direction())
explorer.add_new_scann((1, 2), [Direction.EAST, Direction.NORTH, Direction.WEST, Direction.SOUTH], Direction.WEST,1)
print(explorer.get_next_direction())
explorer.set_choosed_direction(explorer.get_next_direction())
explorer.add_new_scann((1, 2), [Direction.EAST, Direction.NORTH, Direction.WEST, Direction.SOUTH], Direction.SOUTH,1)
print(explorer.get_next_direction())
explorer.set_choosed_direction(explorer.get_next_direction())
explorer.add_new_scann((1, 1), [Direction.WEST, Direction.SOUTH, Direction.NORTH], Direction.SOUTH,1)
print(explorer.get_next_direction())
explorer.set_choosed_direction(explorer.get_next_direction())
explorer.add_new_scann((1, 2), [Direction.WEST, Direction.NORTH], Direction.NORTH,1)
print(explorer.get_next_direction())
explorer.set_choosed_direction(explorer.get_next_direction())
explorer.add_new_scann((0, 1), [Direction.EAST, Direction.SOUTH, Direction.NORTH], Direction.SOUTH,1)
print(explorer.get_next_direction())
explorer.set_choosed_direction(explorer.get_next_direction())
explorer.add_new_scann((0, 0), [Direction.EAST, Direction.SOUTH], Direction.SOUTH,1)
print(explorer.get_next_direction())
explorer.set_choosed_direction(explorer.get_next_direction())
print(planet.path_length(planet.shortest_path((0,0),(1,2))))


